language: ruby
rvm: 2.0.0
env:
  global:
    - GIT_COMMITTER_NAME=YOSHIDA Hiroki
    - GIT_COMMITTER_EMAIL=hyoshida@appirits.com
    - GIT_AUTHOR_NAME=YOSHIDA Hiroki
    - GIT_AUTHOR_EMAIL=hyoshida@appirits.com
    - secure: RQ5SnDfyE19xvqqpYxQU7c0PDw0PUWoIbO7s87xkzdomiYFsD53eb6MpK36zQIS3sAl5QD5JtmaN7vKQwovHZw/hWlq6YKfficX92H5vzMtoly0c8jM38CWBRGbmS/3gVh3GUnMbNdobk9eMU9PFMcX8Ut+mX1SypRvWXhiOldc=
before_script:
  - REV=`git rev-parse HEAD`
  - git clone --quiet --quiet https://github.com/hyoshida/appirits_band_club.git build
  - cd build
  - git checkout gh-pages
  - cd -
  - npm install -g bower
  - bower install
script:
  - bundle exec middleman build
after_success:
  - cd build
  - git add -A
  - git commit -m "Update for \"$REV\""
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/hyoshida/appirits_band_club.git gh-pages'
